name: E2E Tests (with Docker Compose)

# ============================================================================
# CONFIGURACIÓN DE TRIGGERS
# ============================================================================
#
# Este workflow ejecuta tests E2E completos con docker-compose.
# Está configurado para ejecutarse SOLO MANUALMENTE por defecto.
#
# ⚠️ IMPORTANTE - LÍMITES DE GITHUB ACTIONS:
# - GitHub Free: 2000 minutos/mes (repos privados), ilimitado (públicos)
# - Este workflow consume ~8-10 minutos por ejecución
# - Levanta docker-compose completo (PostgreSQL, Kafka, Zipkin, etc.)
#
# ============================================================================
# CÓMO ACTIVAR/DESACTIVAR ESTE WORKFLOW:
# ============================================================================
#
# OPCIÓN 1: Solo manual (ACTUAL - Recomendado)
# ✅ Ejecutar solo cuando lo necesites desde GitHub UI
# ✅ No consume minutos automáticamente
# ✅ Ideal para validación antes de releases
#
# OPCIÓN 2: Automático en Pull Requests (DESACTIVADO)
# Para activar, descomenta las líneas marcadas con [AUTO-PR]
# ⚠️ Consumirá minutos en cada PR
#
# OPCIÓN 3: Automático en Push a Main (DESACTIVADO)
# Para activar, descomenta las líneas marcadas con [AUTO-MAIN]
# ⚠️ Consumirá minutos en cada push a main
#
# OPCIÓN 4: Scheduled (DESACTIVADO)
# Para activar, descomenta las líneas marcadas con [SCHEDULED]
# ⚠️ Consumirá minutos semanalmente
# ============================================================================

on:
  # ✅ ACTIVADO: Ejecutar manualmente desde GitHub UI
  # Ir a: Actions > E2E Tests > Run workflow
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode'
        required: false
        default: 'local'
        type: choice
        options:
          - local
          - docker

      skip_infra:
        description: 'Skip infrastructure startup (if already running)'
        required: false
        default: false
        type: boolean

  # ❌ DESACTIVADO: Ejecutar en Pull Requests
  # [AUTO-PR] Descomenta las siguientes líneas para activar:
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #     - 'src/**'
  #     - 'pom.xml'
  #     - 'docker-compose.yml'
  #     - '.github/workflows/e2e-tests.yml'

  # ❌ DESACTIVADO: Ejecutar en Push a Main
  # [AUTO-MAIN] Descomenta las siguientes líneas para activar:
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'src/**'
  #     - 'pom.xml'

  # ❌ DESACTIVADO: Ejecutar semanalmente
  # [SCHEDULED] Descomenta las siguientes líneas para activar:
  # schedule:
  #   - cron: '0 3 * * 1'  # Cada lunes a las 3am UTC

# ============================================================================
# JOBS
# ============================================================================
jobs:
  e2e-test-local:
    name: E2E Tests (Local Mode - Testcontainers)
    runs-on: ubuntu-latest
    # Solo ejecutar en modo "local" o si no se especificó modo
    if: ${{ !inputs.test_mode || inputs.test_mode == 'local' }}

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🏃 Run E2E tests (Local Mode with Testcontainers)
        run: ./mvnw test -Pe2e-tests -Dkarate.env=local
        env:
          TESTCONTAINERS_RYUK_DISABLED: false

      - name: 📊 Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results-local
          path: |
            target/surefire-reports/
            target/karate-reports/

      - name: 📝 Generate test summary
        if: always()
        run: |
          echo "## 🥒 E2E Test Results (Local Mode)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ -d target/karate-reports ]; then
            echo "✅ E2E tests completed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Test Environment:** Testcontainers (embedded)" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ E2E tests failed" >> $GITHUB_STEP_SUMMARY
          fi

  e2e-test-docker:
    name: E2E Tests (Docker Mode - Full Stack)
    runs-on: ubuntu-latest
    # Solo ejecutar en modo "docker"
    if: ${{ inputs.test_mode == 'docker' }}

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: 🐳 Start infrastructure (docker-compose)
        if: ${{ !inputs.skip_infra }}
        run: |
          echo "🚀 Starting infrastructure..."
          docker-compose up -d
          echo "✅ Infrastructure started"

      - name: ⏳ Wait for services to be ready
        if: ${{ !inputs.skip_infra }}
        run: |
          echo "⏳ Waiting for PostgreSQL..."
          timeout 60 bash -c 'until docker exec hexarch-postgres pg_isready -U postgres; do sleep 2; done'
          echo "✅ PostgreSQL ready"

          echo "⏳ Waiting for Kafka..."
          timeout 60 bash -c 'until docker exec hexarch-kafka kafka-broker-api-versions --bootstrap-server localhost:9092 > /dev/null 2>&1; do sleep 2; done'
          echo "✅ Kafka ready"

          echo "⏳ Waiting for Zipkin..."
          timeout 30 bash -c 'until curl -s http://localhost:9411/health > /dev/null; do sleep 2; done'
          echo "✅ Zipkin ready"

          echo "✅ All services ready!"

      - name: 📋 Show running containers
        run: docker ps

      - name: 🏗️ Build application
        run: ./mvnw clean package -DskipTests

      - name: 🚀 Start application
        run: |
          nohup java -jar target/*.jar > application.log 2>&1 &
          echo $! > application.pid
          echo "Application started with PID: $(cat application.pid)"

      - name: ⏳ Wait for application to be ready
        run: |
          echo "⏳ Waiting for application..."
          timeout 60 bash -c 'until curl -s http://localhost:8080/actuator/health | grep -q "UP"; do sleep 2; done'
          echo "✅ Application ready!"

      - name: 🥒 Run E2E tests (Docker Mode)
        run: ./mvnw test -Pe2e-tests -Dkarate.env=docker
        continue-on-error: false

      - name: 📊 Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results-docker
          path: |
            target/surefire-reports/
            target/karate-reports/
            application.log

      - name: 🔍 Show application logs (if failed)
        if: failure()
        run: |
          echo "=== Application Logs ==="
          cat application.log || echo "No application logs found"

      - name: 🔍 Show docker logs (if failed)
        if: failure()
        run: |
          echo "=== PostgreSQL Logs ==="
          docker logs hexarch-postgres || true
          echo "=== Kafka Logs ==="
          docker logs hexarch-kafka || true

      - name: 🛑 Stop application
        if: always()
        run: |
          if [ -f application.pid ]; then
            kill $(cat application.pid) || true
          fi

      - name: 🛑 Stop infrastructure
        if: always()
        run: |
          docker-compose down -v
          docker system prune -f

      - name: 📝 Generate test summary
        if: always()
        run: |
          echo "## 🥒 E2E Test Results (Docker Mode)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ -d target/karate-reports ]; then
            echo "✅ E2E tests completed with full infrastructure" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Test Environment:** Docker Compose (full stack)" >> $GITHUB_STEP_SUMMARY
            echo "- PostgreSQL: ✅" >> $GITHUB_STEP_SUMMARY
            echo "- Kafka + Zookeeper: ✅" >> $GITHUB_STEP_SUMMARY
            echo "- Zipkin: ✅" >> $GITHUB_STEP_SUMMARY
            echo "- Prometheus + Grafana: ✅" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ E2E tests failed" >> $GITHUB_STEP_SUMMARY
          fi

# ============================================================================
# NOTAS IMPORTANTES
# ============================================================================
#
# 1. MODO LOCAL vs DOCKER:
#    - Local: Usa Testcontainers (más rápido, ~5 min)
#    - Docker: Usa docker-compose (más completo, ~10 min)
#
# 2. CONSUMO DE MINUTOS:
#    - Local Mode: ~5-6 minutos
#    - Docker Mode: ~10-12 minutos
#
# 3. CÓMO EJECUTAR MANUALMENTE:
#    - Ir a: Actions > E2E Tests (with Docker Compose) > Run workflow
#    - Seleccionar modo: local o docker
#    - Opcional: Skip infrastructure startup si ya está corriendo
#
# 4. RECOMENDACIONES:
#    - Usar Local Mode para testing rápido
#    - Usar Docker Mode para validación completa antes de releases
#    - Mantener desactivado el trigger automático para ahorrar minutos
#    - Activar solo cuando sea necesario (antes de releases importantes)
#
# ============================================================================
